version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: property_finder
      MYSQL_USER: property
      MYSQL_PASSWORD: finder
    volumes:
      - ~/.docker/data/rails-property-finder:/var/lib/mysql
  proxy:
    build:
      context: .
    ports:
      - '3000:80'
    volumes:
      - .:/usr/src/app
    links:
      - mysql
